<?php $__env->startSection('body'); ?>
<!-- Start Banner Area -->
<section class="banner-area organic-breadcrumb">
    <div class="container">
    </div>
</section>

<!--================Login Box Area =================-->
	<section class="login_box_area section_gap" style="margin-top: -150px !important">
		<div class="container">
			<h2 style="text-align:center;" >Term and Conditions</h2>
			<div class="row">
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><strong>CONDICIONES GENERALES DE USO.</strong></p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><strong>1 OBJETO.</strong></p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>El presente documento tiene por objeto establecer las Condiciones Generales de Uso del Portal Granyupon.com (en adelante el Portal), titularidad de Otherbets llc. (en adelante Otherbets), con correo electr&oacute;nico info@granyupon.com.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Otherbets se reserva el derecho a modificar las presentes Condiciones Generales de Uso con el objeto de adecuarlas a la legislaci&oacute;n vigente aplicable en cada momento, las novedades jurisprudenciales y las pr&aacute;cticas habituales de mercado.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Las presentes Condiciones Generales de Uso no excluyen la posibilidad de que determinados Servicios del Portal, por sus caracter&iacute;sticas particulares, sean sometidos, adem&aacute;s de a las Condiciones Generales de Uso, a sus propias condiciones particulares de uso (en adelante, las Condiciones Particulares)</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>La utilizaci&oacute;n por parte del Usuario de cualquiera de los Servicios del Portal supone y expresa su adhesi&oacute;n y aceptaci&oacute;n expresa a todas las Condiciones Generales de Uso en la versi&oacute;n publicada en la presente p&aacute;gina web en el momento en que el usuario acceda al Portal, as&iacute; como a las Condiciones Particulares que, en su caso, sean de aplicaci&oacute;n.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><strong>2 CONDICIONES DE ACCESO Y UTILIZACI&Oacute;N DEL PORTAL.</strong></p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Condici&oacute;n de Usuario</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>La aceptaci&oacute;n de las condiciones generales y pol&iacute;tica de privacidad conjuntamente con la utilizaci&oacute;n de cualquier Servicio del Portal atribuye la Condici&oacute;n de Usuario del mismo.</p>
				<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
				    <ol start="1" style="margin-bottom:0cm;list-style-type: lower-alpha;">
				        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Necesidad de Registro</li>
				    </ol>
				</div>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Con car&aacute;cter general para el acceso a los Servicios del Portal no ser&aacute; necesario el Registro del Usuario. No obstante, la utilizaci&oacute;n de determinados Servicios o el alta en nuestras aplicaciones m&oacute;viles podr&aacute; estar condicionada al Registro previo del Usuario.</p>
				<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
				    <ol start="2" style="margin-bottom:0cm;list-style-type: lower-alpha;">
				        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Publicaci&oacute;n de anuncios y perfil p&uacute;blico del usuario</li>
				    </ol>
				</div>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Otherbets llc. se reserva el derecho a difundir y retocar total o parcialmente, los Anuncios del Anunciante en terceros portales, en campa&ntilde;as publicitarias para promocionar el portal tanto propias como de terceras empresas con las que el portal pueda llegar a acuerdos, as&iacute; como en otros sitios web, tales como redes sociales o blogs, aceptando el Anunciante dicha condici&oacute;n por el m&aacute;ximo plazo previsto en la ley y por el mayor &aacute;mbito geogr&aacute;fico posible.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Otherbets. llc har&aacute; visible en los anuncios publicados y en las conversaciones de chat el perfil p&uacute;blico del Usuario (en la que aparece la imagen que haya seleccionado y en el caso de que haya utilizado Facebook la de su perfil social). Otherbets llc. se reserva el derecho a retirar aquellas im&aacute;genes de perfil que considere pueden infringir la normativa vigente os los criterios de conducta del Portal.</p>
				<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
				    <ol start="3" style="margin-bottom:0cm;list-style-type: lower-alpha;">
				        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Uso del Portal y sus Servicios</li>
				    </ol>
				</div>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>El Usuario reconoce y acepta que el uso de los contenidos y/o servicios ofrecidos por granyupon.com ser&aacute; bajo su exclusivo riesgo y/o responsabilidad.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>El Usuario se compromete a utilizar el Portal y todo su contenido y Servicios conforme a lo establecido en la ley, la moral, el orden p&uacute;blico y en las presentes Condiciones Generales de Uso, y en las Condiciones Particulares que, en su caso, le sean de aplicaci&oacute;n. Asimismo, se compromete hacer un uso adecuado de los servicios y/o contenidos del Portal y a no emplearlos para realizar actividades il&iacute;citas o constitutivas de delito, que atenten contra los derechos de terceros y/o que infrinjan la regulaci&oacute;n sobre propiedad intelectual e industrial, o cualesquiera otras normas del ordenamiento jur&iacute;dico aplicable.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>El Usuario se compromete a no trasmitir, introducir, difundir y poner a disposici&oacute;n de terceros, cualquier tipo de material e informaci&oacute;n (datos contenidos, mensajes, dibujos, archivos de sonido e imagen, fotograf&iacute;as, software, etc.) que sean contrarios a la ley, la moral, el orden p&uacute;blico y las presentes Condiciones Generales de Uso y, en su caso, a las Condiciones Particulares que le sean de aplicaci&oacute;n. A t&iacute;tulo enunciativo, y en ning&uacute;n caso limitativo o excluyente, el Usuario se compromete a:</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>1&ordm; No introducir o difundir contenidos o propaganda de car&aacute;cter racista, xen&oacute;fobo, pornogr&aacute;fico, de apolog&iacute;a del terrorismo o que atenten contra los derechos humanos.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>2&ordm; No introducir o difundir en la red programas de datos (virus y software nocivo) susceptibles de provocar da&ntilde;os en los sistemas inform&aacute;ticos del proveedor de acceso, sus proveedores o terceros usuarios de la red Internet.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>3&ordm; No difundir, transmitir o poner a disposici&oacute;n de terceros cualquier tipo de informaci&oacute;n, elemento o contenido que atente contra los derechos fundamentales y las libertades p&uacute;blicas reconocidos constitucionalmente y en los tratados internacionales.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>4&ordm; No difundir, transmitir o poner a disposici&oacute;n de terceros cualquier tipo de informaci&oacute;n, elemento o contenido que constituya publicidad il&iacute;cita o desleal.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>5&ordm; No transmitir publicidad no solicitada o autorizada, material publicitario, &quot;correo basura&quot;, &quot;cartas en cadena&quot;, &quot;estructuras piramidales&quot;, o cualquier otra forma de solicitaci&oacute;n, excepto en aquellas &aacute;reas (tales como espacios comerciales) que hayan sido exclusivamente concebidas para ello.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>6&ordm; No introducir o difundir cualquier informaci&oacute;n y contenidos falsos, ambiguos o inexactos de forma que induzca a error a los receptores de la informaci&oacute;n.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>7&ordm; No suplantar a otros usuarios utilizando sus claves de registro a los distintos servicios y/o contenidos del Portal.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>8&ordm; No difundir, transmitir o poner a disposici&oacute;n de terceros cualquier tipo de informaci&oacute;n, elemento o contenido que suponga una violaci&oacute;n de los derechos de propiedad intelectual e industrial, patentes, marcas o copyright que correspondan a los titulares del Portal o a terceros.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>9&ordm; No difundir, transmitir o poner a disposici&oacute;n de terceros cualquier tipo de informaci&oacute;n, elemento o contenido que suponga una violaci&oacute;n del secreto de las comunicaciones y la legislaci&oacute;n de datos de car&aacute;cter personal.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>10&ordm; No incluir en nuestras p&aacute;ginas, contenidos que indiquen o promuevan discriminaci&oacute;n sexual, racial, religiosa o cualquier otra vulneraci&oacute;n de los derechos fundamentales y las libertades reconocidas por las leyes de Espa&ntilde;a; que induzcan o inciten a actuar de forma ilegal o lleven a conclusiones err&oacute;neas por inexactitud, omisi&oacute;n o similares; que contengan informaci&oacute;n falsa o caduca; que infrinjan normas legales o reglamentarias sobre secreto de las comunicaciones, propiedad intelectual, derecho al honor y a la intimidad personal, o que incorporen contenidos, mensajes o productos violentos o degradantes.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><strong>3 PROPIEDAD INTELECTUAL E INDUSTRIAL.</strong></p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><strong>&nbsp;</strong></p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>El Usuario reconoce que todos los elementos del Portal y de cada uno de los Servicios prestados a trav&eacute;s del mismo, la informaci&oacute;n y materiales contenidos en el mismo, la estructura, selecci&oacute;n, ordenaci&oacute;n y presentaci&oacute;n de sus contenidos y los programas de ordenador utilizados en relaci&oacute;n con el mismo est&aacute;n protegidos por derechos de propiedad intelectual e industrial de Otherbets o de terceros.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Salvo que fuera autorizado por otherbets o, en su caso, por los terceros titulares de los derechos correspondientes, o a menos que ello resulte legalmente permitido, el usuario no podr&aacute; reproducir, transformar, modificar, desensamblar, realizar ingenier&iacute;a inversa, distribuir, alquilar, prestar, poner a disposici&oacute;n o permitir el acceso al p&uacute;blico a trav&eacute;s de cualquier modalidad de comunicaci&oacute;n p&uacute;blica de ninguno de los elementos referidos en el p&aacute;rrafo anterior.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>En particular, queda terminantemente prohibido la utilizaci&oacute;n de los textos, im&aacute;genes, anuncios y otro elemento incluido en el presente sitio web para su posterior inclusi&oacute;n, total o parcial, en otros sitios web ajenos al Portal sin contar con la autorizaci&oacute;n previa y por escrito del Portal.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>El Usuario deber&aacute; abstenerse de suprimir los signos identificativos de los derechos (de propiedad intelectual, industrial o cualquier otro) de otherbets o de los terceros que figuren en el Portal y en cada uno de los diversos Servicios ofrecidos a trav&eacute;s de &eacute;l. Asimismo, el Usuario deber&aacute; abstenerse de eludir o manipular cualesquiera dispositivos t&eacute;cnicos establecidos por otherbets o por terceros, ya sea en el Portal, en cualquiera de los Servicios o en cualquiera de los materiales, elementos o informaci&oacute;n obtenidos a trav&eacute;s del mismo, para la protecci&oacute;n de sus derechos.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Al subir fotograf&iacute;as al Portal, el usuario cede gratuitamente a otherbets los derechos de explotaci&oacute;n de propiedad intelectual sobre las mismas, por lo que otherbets podr&aacute; reproducirlas, transformarlas (incluyendo, sin limitaci&oacute;n, la inclusi&oacute;n de marcas de agua u otros mecanismos que impidan el aprovechamiento inconsentido por parte de terceros), distribuirlas y comunicarlas al p&uacute;blico (incluida la puesta a disposici&oacute;n del p&uacute;blico) a trav&eacute;s de cualquier modalidad de explotaci&oacute;n y utilizando cualquier formato o soporte o medio de explotaci&oacute;n o comunicaci&oacute;n. Dicha cesi&oacute;n de derechos no est&aacute; sujeta a ninguna limitaci&oacute;n de car&aacute;cter temporal ni territorial, esto es, se realiza para todo el mundo y por todo el tiempo de vigencia legal de los mismos. otherbets podr&aacute; ejercer los derechos de explotaci&oacute;n de las fotograf&iacute;as en la forma que estime m&aacute;s conveniente, y podr&aacute; incluso transmitirlos o cederlos con car&aacute;cter exclusivo o no a terceros en los t&eacute;rminos y condiciones que considere oportunos.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>El usuario garantiza que es pleno titular de los derechos que se ceden a otherbets en virtud de esta cl&aacute;usula, y que el uso y explotaci&oacute;n de los mismos por otherbets no supondr&aacute; violaci&oacute;n alguna de derechos de propiedad intelectual, ni de imagen, ni, en general, de ninguna otra clase, que correspondan a cualesquiera terceros, oblig&aacute;ndose a indemnizar y a mantener indemne a otherbets en caso de infracci&oacute;n.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><strong>4 EXCLUSI&Oacute;N DE GARANT&Iacute;AS. RESPONSABILIDAD</strong></p>
				<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
				    <ol start="1" style="margin-bottom:0cm;list-style-type: upper-alpha;">
				        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Disponibilidad y Continuidad del Portal y los Servicios</li>
				    </ol>
				</div>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Otherbets no garantiza la disponibilidad, acceso y continuidad del funcionamiento del Portal y de sus Servicios.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Otherbets no ser&aacute; responsable, con los l&iacute;mites establecidos en el ordenamiento jur&iacute;dico vigente, de los da&ntilde;os y perjuicios causados al Usuario como consecuencia de la indisponibilidad, fallos de acceso y falta de continuidad del Portal y sus Servicios.</p>
				<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
				    <ol start="2" style="margin-bottom:0cm;list-style-type: upper-alpha;">
				        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Contenidos y Servicios de Otherbets</li>
				    </ol>
				</div>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Otherbets responder&aacute; &uacute;nica y exclusivamente de los Servicios que preste por s&iacute; misma y de los contenidos directamente originados por Otherbets e identificados con su copyright. Dicha responsabilidad quedar&aacute; excluida en los casos en que concurran causas de fuerza mayor o en los supuestos en que la configuraci&oacute;n de los equipos del Usuario no sea la adecuada para permitir el correcto uso de los servicios de Internet prestados por Otherbets. En cualquier caso, la eventual responsabilidad de Otherbets frente al usuario por todos los conceptos quedar&aacute; limitada como m&aacute;ximo al importe de las cantidades percibidas directamente del usuario por Otherbets, con exclusi&oacute;n en todo caso de responsabilidad por da&ntilde;os indirectos o por lucro cesante.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>El portal no se hace responsable del mantenimiento por parte de terceros (como los que se indican aqu&iacute; a t&iacute;tulo enunciativo, y en ning&uacute;n caso limitativo o excluyente: sitios webs, agregadores, plataformas de pagos, redes sociales o blogs) una vez el anuncio se de baja de nuestras bases de datos.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Destacar a su vez, que el portal no se hace responsable de la posible aparici&oacute;n de anuncios indexados en buscadores ajenos al portal, una vez se hayan dado de baja de nuestras bases de datos.</p>
				<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
				    <ol start="3" style="margin-bottom:0cm;list-style-type: upper-alpha;">
				        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Contenidos y Servicios de Terceros</li>
				    </ol>
				</div>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Otherbets no controla previamente, aprueba ni hace propios los contenidos, servicios, opiniones, comunicaciones datos, archivos, productos y cualquier clase de informaci&oacute;n de terceros, personas jur&iacute;dicas o f&iacute;sicas, recogidos en el Portal. De igual forma, no garantiza la licitud, fiabilidad, utilidad, veracidad, exactitud, exhaustividad y actualidad de los contenidos, informaciones y Servicios de terceros en el Portal.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Otherbets no controla con car&aacute;cter previo y no garantiza la ausencia de virus y otros elementos en los Contenidos y servicios prestados por terceros a trav&eacute;s del Portal que puedan introducir alteraciones en el sistema inform&aacute;tico, documentos electr&oacute;nicos o ficheros de los usuarios.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Otherbets no ser&aacute; responsable, ni indirectamente ni subsidiariamente, de los da&ntilde;os y perjuicios de cualquier naturaleza derivados de la utilizaci&oacute;n y contrataci&oacute;n de los Contenidos y de los Servicios de terceros en el Portal as&iacute; como de la falta de licitud, fiabilidad, utilidad, veracidad, exactitud, exhaustividad y actualidad de los mismos. Con car&aacute;cter enunciativo, y en ning&uacute;n caso limitativo, no ser&aacute; responsable por los da&ntilde;os y perjuicios de cualquier naturaleza derivados de a) la infracci&oacute;n de los derechos propiedad intelectual e industrial y el cumplimiento defectuoso o incumplimiento de los compromisos contractuales adquiridos por terceros; b) la realizaci&oacute;n de actos de competencia desleal y publicidad il&iacute;cita; c) la inadecuaci&oacute;n y defraudaci&oacute;n de las expectativas de los Servicios y Contenidos de los terceros; d) los vicios y defectos de toda clase de los Servicios y contenidos de terceros prestados a trav&eacute;s del Portal.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Otherbets no ser&aacute; responsable, ni indirectamente ni subsidiariamente, de los da&ntilde;os y perjuicios de cualquier naturaleza derivados de la utilizaci&oacute;n negligente o malintencionada de las cuentas de correo electr&oacute;nico utilizadas para cualquier tipo de inserci&oacute;n, comunicaci&oacute;n, gesti&oacute;n o actuaci&oacute;n en el Portal.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Otherbets no ser&aacute; responsable, ni indirectamente ni subsidiariamente, de los da&ntilde;os y perjuicios de cualquier naturaleza causados al Usuario como consecuencia de la presencia de virus u otros elementos en los contenidos y Servicios prestados por terceros que puedan producir alteraciones en el sistema inform&aacute;tico, documentos electr&oacute;nicos o ficheros de los usuarios.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>La exoneraci&oacute;n de responsabilidad se&ntilde;alada en los p&aacute;rrafos anteriores ser&aacute; de aplicaci&oacute;n en el caso de que Otherbets no tenga conocimiento efectivo de que la actividad o la informaci&oacute;n almacenada es il&iacute;cita o de que lesiona bienes o derechos de un tercero susceptibles de indemnizaci&oacute;n, o si la tuviesen act&uacute;en con diligencia para retirar los datos y contenidos o hacer imposible el acceso a ellos.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
				<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
				    <ol start="4" style="margin-bottom:0cm;list-style-type: upper-alpha;">
				        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Conducta de los Usuarios</li>
				    </ol>
				</div>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Otherbets no garantiza que los Usuarios del Portal utilicen los contenidos y/o servicios del mismo de conformidad con la ley, la moral, el orden p&uacute;blico, ni las presentes Condiciones Generales y, en su caso, las condiciones Particulares que resulten de aplicaci&oacute;n. Asimismo, no garantiza la veracidad y exactitud, exhaustividad y/o autenticidad de los datos proporcionados por los Usuarios.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Otherbets no ser&aacute; responsable, indirecta ni subsidiariamente, de los da&ntilde;os y perjuicios de cualquier naturaleza derivados de la utilizaci&oacute;n de los Servicios y Contenidos del Portal por parte de los Usuarios o que puedan derivarse de la falta de veracidad, exactitud y/o autenticidad de los datos o informaciones proporcionadas por los Usuarios, o de la suplantaci&oacute;n de la identidad de un tercero efectuada por un Usuario en cualquier clase de actuaci&oacute;n a trav&eacute;s del Portal. A t&iacute;tulo enunciativo, pero no limitativo, &nbsp;Otherbets no ser&aacute; responsable indirecta o subsidiariamente de a) los contenidos, informaciones, opiniones y manifestaciones de cualquier Usuario o de terceras personas o entidades que se comuniquen o exhiban a trav&eacute;s del Portal; b) los da&ntilde;os y perjuicios causados a terceros derivados de la utilizaci&oacute;n por parte del Usuario de los servicios y contenidos del Portal; c) Los da&ntilde;os y perjuicios causados por la falta de veracidad, exactitud o incorrecci&oacute;n de la identidad de los usuarios y de toda informaci&oacute;n que &eacute;stos proporcionen o hagan accesible a otros usuarios; d) de los da&ntilde;os y perjuicios derivados de infracciones de cualquier usuario que afecten a los derechos de otro usuario, o de terceros, incluyendo los derechos de copyright, marca, patentes, informaci&oacute;n confidencial y cualquier otro derecho de propiedad intelectual e industrial.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><strong>5 CONTRATACI&Oacute;N CON TERCEROS A TRAV&Eacute;S DEL PORTAL.</strong></p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>El Usuario reconoce y acepta que cualquier relaci&oacute;n contractual o extracontractual que, en su caso, formalice con los anunciantes o terceras personas contactadas a trav&eacute;s del Portal, as&iacute; como su participaci&oacute;n en concursos, promociones, compraventa de bienes o servicios, se entienden realizados &uacute;nica y exclusivamente entre el Usuario y el anunciante y/o tercera persona. En consecuencia, el Usuario acepta que Otherbets no tiene ning&uacute;n tipo de responsabilidad sobre los da&ntilde;os o perjuicios de cualquier naturaleza ocasionados con motivo de sus negociaciones, conversaciones y/o relaciones contractuales o extracontractuales con los anunciantes o terceras personas f&iacute;sicas o jur&iacute;dicas contactadas a trav&eacute;s del Portal.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><strong>6 DISPOSITIVOS T&Eacute;CNICOS DE ENLACE TEXTUAL</strong></p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>El Portal pone a disposici&oacute;n de los clientes (especialmente habilitados para ello) dispositivos t&eacute;cnicos de enlace y herramientas de b&uacute;squeda que permiten a los Usuarios el acceso a p&aacute;ginas web titularidad de otras entidades (enlaces textuales).</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>El cliente debidamente autorizado reconoce y acepta que la utilizaci&oacute;n de los contenidos de las p&aacute;ginas web enlazadas ser&aacute; bajo su exclusivo riesgo y responsabilidad y exonera a Otherbets de cualquier responsabilidad sobre disponibilidad t&eacute;cnica de las p&aacute;ginas web enlazadas, la calidad, fiabilidad exactitud y/o veracidad de los servicios, informaciones, elementos y/o contenidos a los que el cliente pueda acceder en las mismas y en los directorios de b&uacute;squeda incluidos en el Portal.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Otherbets no ser&aacute; responsable indirecta ni subsidiariamente de los da&ntilde;os y perjuicios de cualquier naturaleza derivados de a) el funcionamiento, indisponibilidad, inaccesibilidad y la ausencia de continuidad de las p&aacute;ginas web enlazadas y/o los directorios de b&uacute;squeda disponibles; b) la falta de mantenimiento y actualizaci&oacute;n de los contenidos y servicios contenidos en las p&aacute;ginas web enlazadas; c) la falta de calidad, inexactitud, ilicitud, inutilidad de los contenidos y servicios de las p&aacute;ginas web enlazadas.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>La exoneraci&oacute;n de responsabilidad se&ntilde;alada en los p&aacute;rrafos anteriores ser&aacute; de aplicaci&oacute;n en el caso de que Otherbets no tenga conocimiento efectivo de que la actividad o la informaci&oacute;n a la que remite es l&iacute;cita o de que lesiona bienes o derechos de un tercero susceptibles de indemnizaci&oacute;n o, si la tuviese, act&uacute;e con diligencia para retirar los datos y contenidos o hacer imposible el acceso a ellos.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><strong>7 PROTECCI&Oacute;N DE DATOS DE CAR&Aacute;CTER PERSONAL</strong></p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Antes de completar el Registro de Usuarios deber&aacute; leer y aceptar la siguiente informaci&oacute;n sobre Protecci&oacute;n de Datos y Ley de Servicios de la Sociedad de la Informaci&oacute;n.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><strong>8 VARIOS</strong></p>
				<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
				    <ol start="1" style="margin-bottom:0cm;list-style-type: upper-alpha;">
				        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Modificaciones</li>
				    </ol>
				</div>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Otherbets se reserva el derecho a efectuar las modificaciones que estime oportunas, pudiendo modificar, suprimir e incluir, unilateralmente y sin previo aviso, nuevos contenidos y/o servicios, as&iacute; como la forma en que &eacute;stos aparezcan presentados y localizados.</p>
				<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
				    <ol start="2" style="margin-bottom:0cm;list-style-type: upper-alpha;">
				        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Derecho de exclusi&oacute;n</li>
				    </ol>
				</div>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Otherbets se reserva el derecho a denegar o retirar el acceso al Portal y/o los servicios ofrecidos, sin necesidad de preaviso a instancia propia o de un tercero, a aquellos usuarios que pudieran estar incumpliendo las presentes Condiciones Generales de Uso y/o las condiciones Particulares que, en su caso, resulten de aplicaci&oacute;n.</p>
				<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
				    <ol start="3" style="margin-bottom:0cm;list-style-type: upper-alpha;">
				        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Menores de Edad</li>
				    </ol>
				</div>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Con car&aacute;cter general, para hacer uso de los Servicios del Portal los menores de edad deben haber obtenido previamente la autorizaci&oacute;n de sus padres, tutores o representantes legales, quienes ser&aacute;n responsables de todos los actos realizados a trav&eacute;s del Portal por los menores a su cargo. En aquellos Servicios en los que expresamente se se&ntilde;ale, el acceso quedar&aacute; restringido &uacute;nica y exclusivamente a mayores de 18 a&ntilde;os.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><strong>9 DURACI&Oacute;N Y TERMINACI&Oacute;N</strong></p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>La prestaci&oacute;n de los servicios y/o contenidos del Portal tiene una duraci&oacute;n indefinida. Sin perjuicio de lo anterior, Otherbets est&aacute; facultada para dar por terminada, suspender o interrumpir unilateralmente, en cualquier momento y sin necesidad de preaviso, la prestaci&oacute;n del servicio y del Portal y/o de cualquiera de los servicios, sin perjuicio de lo que se hubiera dispuesto al respecto en las correspondientes condiciones particulares.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><strong>10 LEY Y JURISDICCI&Oacute;N</strong></p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Las partes se someten a su elecci&oacute;n, para la resoluci&oacute;n de los conflictos y con renuncia a cualquier otro fuero, a los juzgados y tribunales del domicilio del usuario. Asimismo, como entidad adherida a Confianza Online y en los t&eacute;rminos de su C&oacute;digo &Eacute;tico, en caso de controversias relativas a la contrataci&oacute;n y publicidad online, protecci&oacute;n de datos y protecci&oacute;n de menores, el usuario podr&aacute; acudir al sistema de resoluci&oacute;n extrajudicial de controversias de Confianza Online (<a href="http://www.confianzaonline.es">www.confianzaonline.es</a>).</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><strong>CONDICIONES PARTICULARES DE CONTRATACI&Oacute;N DEL SERVICIO DE ANUNCIOS y VENTAS.</strong></p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><strong>1 Condiciones Particulares de Contrataci&oacute;n.</strong></p>
				<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
				    <ol start="1" style="margin-bottom:0cm;list-style-type: upper-alpha;">
				        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>El presente documento tiene por objeto establecer las Condiciones Particulares de Uso y Contrataci&oacute;n Online del Servicio ANUNCIOS Y VENTAS (en adelante el Servicio) prestado por en Otherbets el Portal.</li>
				    </ol>
				</div>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:36.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
				<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
				    <ol start="2" style="margin-bottom:0cm;list-style-type: upper-alpha;">
				        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>La utilizaci&oacute;n y contrataci&oacute;n del Servicio supone y expresa la adhesi&oacute;n y aceptaci&oacute;n expresa del Anunciante a las presentes Condiciones Particulares de Uso y Contrataci&oacute;n v&iacute;a Online del Servicio, as&iacute; como a las Condiciones Generales de Uso de Portal, constituyendo ambos documentos las Condiciones Generales de Contrataci&oacute;n que regir&aacute;n la relaci&oacute;n formalizada entre el Anunciante y Otherbets (en adelante las CONDICIONES GENERALES DE CONTRATACI&Oacute;N). El Anunciante acepta como v&aacute;lida la contrataci&oacute;n v&iacute;a online de las CONDICIONES GENERALES DE CONTRATACI&Oacute;N.</li>
				    </ol>
				</div>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:36.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
				<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
				    <ol start="3" style="margin-bottom:0cm;list-style-type: upper-alpha;">
				        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>En caso de Discrepancia entre las Condiciones Generales de Uso de Portal y las Condiciones Particulares de Uso y Contrataci&oacute;n v&iacute;a Online del Servicio ser&aacute; de aplicaci&oacute;n lo establecido en &eacute;ste &uacute;ltimo documento.</li>
				    </ol>
				</div>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><strong>2 Descripci&oacute;n del Servicio</strong></p>
				<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
				    <ol start="1" style="margin-bottom:0cm;list-style-type: upper-alpha;">
				        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>El Servicio consiste en la inserci&oacute;n de anuncios (PRODUCTOS) en el Portal. El anuncio se publicar&aacute; en Granyupon.com. Dicho env<span style="font-family:Calibri;">i</span>&oacute; y publicaci<span style="font-family:Calibri;">&oacute;</span>n implica que el anuncio, as<span style="font-family:Calibri;">&iacute;</span> como las fotograf<span style="font-family:Calibri;">&iacute;</span>as y los datos facilitados, se repliquen en los portales de destino en funci<span style="font-family:Calibri;">&oacute;</span>n de sus caracter<span style="font-family:Calibri;">&iacute;</span>sticas y requisitos t<span style="font-family:Calibri;">&eacute;</span>cnicos. Desde su &aacute;rea de usuario del Portal, pero utilizando la versi&oacute;n m&oacute;vil o desktop (no desde las aplicaciones m&oacute;viles) del mismo, el usuario podr&aacute; en todo momento editar el anuncio seleccionando.</li>
				    </ol>
				</div>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
				<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
				    <ol start="2" style="margin-bottom:0cm;list-style-type: upper-alpha;">
				        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Otherbets llc. se reserva el derecho a difundir en terceros portales, total o parcialmente, los Anuncios del Anunciante, as&iacute; como en otros sitios web, tales como redes sociales o blogs, aceptando el Anunciante dicha condici&oacute;n.</li>
				    </ol>
				</div>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:35.45pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Asimismo, al subir fotograf&iacute;as al Portal, el usuario cede gratuitamente a Otherbets los derechos de explotaci&oacute;n de propiedad intelectual sobre las mismas, por lo que Otherbets podr&aacute; reproducirlas, transformarlas (incluyendo, sin limitaci&oacute;n, la inclusi&oacute;n de marcas de agua u otros mecanismos que impidan el aprovechamiento inconsentido por parte de terceros), distribuirlas y comunicarlas al p&uacute;blico (incluida la puesta a disposici&oacute;n del p&uacute;blico) a trav&eacute;s de cualquier modalidad de explotaci&oacute;n y utilizando cualquier formato o soporte o medio de explotaci&oacute;n o comunicaci&oacute;n. Dicha cesi&oacute;n de derechos no est&aacute; sujeta a ninguna limitaci&oacute;n de car&aacute;cter temporal ni territorial, esto es, se realiza para todo el mundo y por todo el tiempo de vigencia legal de los mismos. Otherbets podr&aacute; ejercer los derechos de explotaci&oacute;n de las fotograf&iacute;as en la forma que estime m&aacute;s conveniente, y podr&aacute; incluso transmitirlos o cederlos con car&aacute;cter exclusivo o no a terceros en los t&eacute;rminos y condiciones que considere oportunos.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:35.45pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>El usuario garantiza que es pleno titular de los derechos que se ceden a Otherbets en virtud de esta cl&aacute;usula, y que el uso y explotaci&oacute;n de los mismos por Otherbets no supondr&aacute; violaci&oacute;n alguna de derechos de propiedad intelectual, ni de imagen, ni, en general, de ninguna otra clase, que correspondan a cualesquiera terceros, oblig&aacute;ndose a indemnizar y a mantener indemne a Otherbets en caso de infracci&oacute;n.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:35.45pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><strong>3 Procedimiento de Contrataci&oacute;n del Servicio</strong></p>
				<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
				    <ol start="1" style="margin-bottom:0cm;list-style-type: upper-alpha;">
				        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Para insertar anuncios en el Portal el anunciante ha de completar el formulario de alta de vendedor. Una vez Creado el perfil de vendedor e insertado su anuncio, si &eacute;ste cumple las reglas de publicaci&oacute;n de Granyupon.com, el usuario recibir&aacute; una notificaci&oacute;n confirm&aacute;ndole la publicaci&oacute;n de su anuncio. En el caso que el anuncio no cumpla las reglas de publicaci&oacute;n de Granyupon.com, el usuario deber&aacute; modificar el anuncio.</li>
				    </ol>
				</div>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:36.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
				<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
				    <ol start="2" style="margin-bottom:0cm;list-style-type: upper-alpha;">
				        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>A partir del Registro de perfil de vendedor los datos del anunciante quedar&aacute;n registrados y podr&aacute; poner y renovar anuncios con tan s&oacute;lo identificarse. Una vez registrado, cada vez que acceda al &aacute;rea de vendedor le solicitaremos su direcci&oacute;n de correo electr&oacute;nico y su clave de acceso para proceder a la inserci&oacute;n o renovaci&oacute;n de anuncios.</li>
				    </ol>
				</div>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:36.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
				<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
				    <ol start="3" style="margin-bottom:0cm;list-style-type: upper-alpha;">
				        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Una vez registrado el usuario podr&aacute; acceder a la inserci&oacute;n y renovaci&oacute;n de anuncios online identific&aacute;ndose utilizando el formulario de acceso a Vendedores introduciendo en el mismo su e-mail y contrase&ntilde;a.</li>
				    </ol>
				</div>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:36.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
				<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
				    <ol start="4" style="margin-bottom:0cm;list-style-type: upper-alpha;">
				        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Cuando un usuario lo desee, podr&aacute; acceder a su cuenta para ver sus anuncios. En cualquier momento, des del panel de administraci&oacute;n podr&aacute; darse de baja de la cuenta.</li>
				    </ol>
				</div>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:36.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
				<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
				    <ol start="5" style="margin-bottom:0cm;list-style-type: upper-alpha;">
				        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Los anuncios permanecer&aacute;n publicados en el Portal por TIEMPO ILIMITADO Y HASTA SU ELIMINACION desde su publicaci&oacute;n o renovaci&oacute;n para todas las categor&iacute;as y para todos los tipos de anunciantes, tanto particulares como profesionales.</li>
				    </ol>
				</div>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:36.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
				<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
				    <ol start="6" style="margin-bottom:0cm;list-style-type: upper-alpha;">
				        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>La eliminaci&oacute;n del Perfil por parte del anunciante o vendedor, supondr&aacute; la finalizaci&oacute;n del servicio y por consiguiente la eliminaci&oacute;n total de todos sus productos u anuncios del portal. Para publicar nuevamente el anuncio o productos eliminados, o cualquier otro, el anunciante deber&aacute; crear un nuevo perfil.</li>
				    </ol>
				</div>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:36.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
				<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
				    <ol start="7" style="margin-bottom:0cm;list-style-type: upper-alpha;">
				        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>El uso de las presentes condiciones particulares de contrataci&oacute;n permiten al anunciante particular la publicaci&oacute;n de anuncios o productos en base a los siguientes criterios:</li>
				    </ol>
				</div>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:36.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
				<ol style="list-style-type: decimal;">
				    <li>Limitaci&oacute;n a productos textiles o prendas de vestir, tales como camisetas, pantalones, trajes, calzado etc. As&iacute; como a complementos de moda. Quedando fuera todo lo que no compete a la vestimenta o a la moda en el grupo textil.</li>
				    <li>Excluyendo de manera clara y concisa todos los productos registrados Tales como marcas, logotipos etc. Sin autorizaci&oacute;n previa del due&ntilde;o/s de la marca.</li>
				</ol>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><strong>4 Contrataci&oacute;n de servicios vinculados al Producto o Anuncio</strong></p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Todos los precios se indican con los impuestos incluidos. Condiciones de pago: Los usuarios particulares deber&aacute;n efectuar el pago mediante tarjetas de cr&eacute;dito a trav&eacute;s del propio Portal. En este caso, no se iniciar&aacute; ning&uacute;n tr&aacute;mite hasta la correcta recepci&oacute;n del comprobante de pago.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>A Los anunciantes tanto particulares como profesionales Se les retendr&aacute; la comisi&oacute;n establecida cuando el usuario realice el pago de los productos anunciados por dicho vendedor. Las comisiones depender&aacute;n de las condiciones pactadas en cada momento.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><strong>5 Normas de Publicaci&oacute;n de los Anuncios</strong></p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Con car&aacute;cter general la publicaci&oacute;n de los Anuncios en el Portal estar&aacute; sujeta a una serie de reglas de publicaci&oacute;n cuyo contenido se puede consultar en el siguiente enlace: REGLAS PARA LA PUBLICACI&Oacute;N DE ANUNCIOS</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><strong>6 Limitaci&oacute;n de la Responsabilidad</strong></p>
				<ol start="1" style="list-style-type: lower-alpha;">
				    <li>El Anunciante reconoce y acepta que la responsabilidad m&aacute;xima de Otherbets frente al Anunciante que pudiera derivarse de la inserci&oacute;n de Anuncios en el Portal es la siguiente: Si Otherbets no insertara el Anuncio en las fechas previstas, si el Anuncio no fuera insertado en la forma y t&eacute;rminos acordados, ya sea por razones t&eacute;cnicas o de cualquier otro tipo, o por cualquier otra causa, la responsabilidad m&aacute;xima queda limitada a la reinserci&oacute;n del Anuncio con posterioridad en una posici&oacute;n semejante y, si ello no fuera posible o si Otherbets as&iacute; lo decidiese, al reembolso de la parte proporcional del precio por Anuncio efectivamente satisfecho por el Anunciante.</li>
				    <li>En ning&uacute;n caso Otherbets responder&aacute; por otro tipo de da&ntilde;os, ya sean efectivos, indirectos, o de cualquier otro tipo, ni por el lucro cesante que hubiera podido sufrir el Anunciante por la falta de publicaci&oacute;n puntual y/o correcta de cualquier Anuncio.</li>
				    <li>Otherbets no responder&aacute; por los retrasos, publicaci&oacute;n err&oacute;nea ni por la falta de la publicaci&oacute;n del anuncio que sean consecuencia de hechos o circunstancias que est&eacute;n fuera de su control, incluido, a t&iacute;tulo enunciativo y no limitativo, acci&oacute;n gubernativa, incendio, inundaci&oacute;n, insurrecci&oacute;n, terremoto, fallo t&eacute;cnico, mot&iacute;n, explosi&oacute;n, embargo, huelga legal o ilegal, escasez de personal o de material, interrupci&oacute;n del transporte de cualquier tipo, retraso en el trabajo, o cualquier otra circunstancia fuera del control de Otherbets.</li>
				</ol>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><strong>7 Manifestaciones y garant&iacute;as del Anunciante/Indemnizaciones</strong></p>
				<ol start="1" style="list-style-type: lower-alpha;">
				    <li>La inserci&oacute;n de Anuncios en el Portal se efect&uacute;a en consideraci&oacute;n a las presentes manifestaciones y garant&iacute;as que efect&uacute;a el Anunciante.</li>
				    <li>El Anunciante tiene derecho a publicar el contenido del Anuncio, sin que ello infrinja la Ley y ning&uacute;n derecho de terceros, incluyendo los derechos de propiedad industrial e intelectual. Ser&aacute; responsabilidad del Anunciante obtener todas las autorizaciones, p&uacute;blicas o privadas, y efectuar todos los pagos por la utilizaci&oacute;n de los derechos de propiedad intelectual e industrial que se contengan en el Anuncio. El Anunciante declara conocer que Otherbets ha aceptado efectuar la inserci&oacute;n del Anuncio sobre la base de la presente manifestaci&oacute;n y garant&iacute;a.</li>
				</ol>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:36.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
				<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
				    <ol start="3" style="margin-bottom:0cm;list-style-type: lower-alpha;">
				        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>El Anunciante, as&iacute; como el Anuncio, su contenido y cualquier material del Anunciante a que puedan acceder los Usuarios del Portal a trav&eacute;s del anuncio, cumplen las normas vigentes sobre publicidad, incluida la efectuada por medios electr&oacute;nicos y online, as&iacute; como cualquier otra normativa aplicable, y, en especial, la relativa a telecomunicaciones, protecci&oacute;n de consumidores y usuarios, derecho al honor, a la intimidad y a la propia imagen, y protecci&oacute;n del menor y de la infancia.</li>
				    </ol>
				</div>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
				<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
				    <ol start="4" style="margin-bottom:0cm;list-style-type: lower-alpha;">
				        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>La inclusi&oacute;n del anuncio en el Portal no supone el incumplimiento ni la violaci&oacute;n de ninguna obligaci&oacute;n legal y/o contractual asumida por el Anunciante con terceras personas.</li>
				    </ol>
				</div>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:36.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:36.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
				<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
				    <ol start="5" style="margin-bottom:0cm;list-style-type: lower-alpha;">
				        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>El Anunciante ser&aacute; el &uacute;nico responsable, frente a los Usuarios del Portal y terceras personas del texto e informaci&oacute;n contenidas en el Anuncio. As&iacute;, a t&iacute;tulo enunciativo y en ning&uacute;n caso limitativo, Otherbets no ser&aacute; responsable, ni directa, ni indirecta ni subsidiaria, de los da&ntilde;os y perjuicios de cualquier naturaleza que puedan derivarse para los usuarios del Portal y/o terceras personas de la falta de veracidad, exactitud y/o autenticidad, legalidad de los datos o informaciones contenidos en el Anuncio insertado.</li>
				    </ol>
				</div>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:36.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
				<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
				    <ol start="6" style="margin-bottom:0cm;list-style-type: lower-alpha;">
				        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>El Anunciante reconoce y acepta que cualquier relaci&oacute;n contractual o extracontractual que, en su caso, formalice con usuarios del Portal o terceras personas contactadas a trav&eacute;s del Portal, se entienden realizados &uacute;nica y exclusivamente entre el Anunciante y el Usuario del Portal y/o la tercera persona. En consecuencia, el Anunciante acepta que Otherbets no tiene ning&uacute;n tipo de responsabilidad, ni directa, ni indirecta ni subsidiaria, sobre los da&ntilde;os o perjuicios de cualquier naturaleza ocasionados a los Usuarios del Portal y/o terceras personas con motivo de las negociaciones, conversaciones y/o relaciones contractuales o extracontractuales que &eacute;stos formalicen con el Anunciante.</li>
				    </ol>
				</div>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:36.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:36.0pt;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
				<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
				    <ol start="7" style="margin-bottom:0cm;list-style-type: lower-alpha;">
				        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>En cualquier caso, el Anunciante accede a indemnizar a Otherbets , inmediatamente que sea requerido para ello, de todos los gastos, costes, perjuicios y p&eacute;rdidas de cualquier tipo (incluyendo honorarios de abogados y procuradores, aunque su intervenci&oacute;n no sea preceptiva) en que incurra Otherbets como consecuencia de cualquier reclamaci&oacute;n, efectiva o inminente, de cualquier tipo, relativa a la publicaci&oacute;n o comunicaci&oacute;n al p&uacute;blico del anuncio o de su contenido, incluyendo las basadas en violaci&oacute;n de derechos de propiedad industrial o intelectual, calumnia, difamaci&oacute;n, incumplimiento de deber de confidencialidad, revelaci&oacute;n de secretos, incumplimiento de cualquier deber legal o reglamentario y/o de publicidad il&iacute;cita, falsa o enga&ntilde;osa.</li>
				    </ol>
				</div>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><strong>8 Derecho a modificar y rechazar el Anuncio por Otherbets</strong></p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Otherbets no se obliga a revisar previamente el contenido de ning&uacute;n Anuncio, y cualquier revisi&oacute;n o aprobaci&oacute;n efectuada por Otherbets no debe entenderse como aceptaci&oacute;n de que dicho Anuncio cumple los t&eacute;rminos de las CONDICIONES GENERALES DE CONTRATACI&Oacute;N.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Otherbets se reserva el derecho, ejercitable en cualquier momento y de modo discrecional, a:</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Rechazar cualquier Anuncio, la orden de inserci&oacute;n de anuncios, o compromiso de ubicaci&oacute;n.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Eliminar cualquier anuncio del Portal o de cualquiera de sus p&aacute;ginas.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Modificar aquellos campos de su anuncio que no cumplan con las normas de inserci&oacute;n del portal, todo ello al objeto de dar mayor calidad al mismo y de acuerdo a las siguientes limitaciones: Otherbets podr&aacute; modificar la ortograf&iacute;&shy;a del texto, la categor&iacute;&shy;a del producto en caso de haberse clasificado mal, la provincia en caso de no concordar con la ciudad indicada, eliminar fotograf&iacute;as en caso de que no sean correctas o adecuadas al anuncio, as&iacute;&shy; como el t&iacute;tulo y el texto del anuncio en caso de contener alguna de las palabras no permitidas por las reglas de publicaci&oacute;n tales como t&iacute;tulos exagerados, exclamaciones, etc. En el resto de casos, si el anuncio no cumple con alguna de las reglas de publicaci&oacute;n, ser&aacute; rechazado y se remitir&aacute; un correo electr&oacute;nico en el que se indicar&aacute; los motivos del rechazo y las instrucciones para poder corregirlo.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><strong>9 Derecho legal a desistir del servicio</strong></p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>El derecho legal de desistimiento es &uacute;nicamente aplicable a consumidores y usuarios. En este sentido, el art&iacute;culo 3 del TRLGDCU, establece que a los efectos de esta norma son consumidores o usuarios las personas f&iacute;sicas o jur&iacute;dicas que act&uacute;an en un &aacute;mbito ajeno a una actividad empresarial o profesional. Por tanto, quedar&aacute;n excluidas las personas f&iacute;sicas o jur&iacute;dicas que en la contrataci&oacute;n del servicio est&eacute;n realizando alguna actividad profesional o empresarial.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>De acuerdo con el art&iacute;culo 103. m) del TRLGDCU, se informa que el consumidor y usuario perder&aacute; de forma autom&aacute;tica el derecho de desistimiento en el mismo momento en que se inicie el Servicio. En este sentido, la contrataci&oacute;n y en su caso la activaci&oacute;n del servicio comporta el inicio de los mismos.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><strong>Varios</strong></p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Otherbets se reserva el derecho a efectuar las modificaciones que estime oportunas en las CONDICIONES GENERALES DE CONTRATACI&Oacute;N, as&iacute; como en los precios del Servicio.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Los precios de los servicios para cada una de las modalidades ser&aacute;n los establecidos en las correspondientes p&aacute;ginas del Portal para cada servicio y ser&aacute;n v&aacute;lidos durante el tiempo que los mismos permanezcan accesibles al Usuario.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Con car&aacute;cter general, Otherbets informa al Anunciante que no archivar&aacute; el documento electr&oacute;nico en el que se formalice la contrataci&oacute;n del Servicio. Asimismo, le informa que el Procedimiento de Contrataci&oacute;n del Servicio y todos los documentos contractuales que regir&aacute;n la relaci&oacute;n formalizada se realizar&aacute;n en lengua espa&ntilde;ola.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>Las CONDICIONES GENERALES DE CONTRATACI&Oacute;N que han de regir la relaci&oacute;n Otherbets y el Anunciante ser&aacute;n de aplicaci&oacute;n desde el inicio del Procedimiento de Contrataci&oacute;n Online del Servicio se&ntilde;alado en el presente Documento hasta la finalizaci&oacute;n del plazo de tiempo por el que ha sido contratada la inserci&oacute;n del Anuncio/s en cualquiera de las ediciones Otherbets La utilizaci&oacute;n y contrataci&oacute;n del Servicios estar&aacute; sujeta a Pol&iacute;tica de Protecci&oacute;n de Datos del Portal.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>El Portal le informa que determinados servidores pueden guardar, en su memoria cach&eacute;, una copia de las p&aacute;ginas consultadas en el portal por los usuarios. Dicha acci&oacute;n se realiza con la finalidad exclusiva de mejorar la velocidad de tr&aacute;fico de las mismas.</p>
				<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>El portal podr&aacute; recoger en momentos puntuales datos completamente disociados para la mejora constante de sus servicios y productos dentro y fuera del portal. Dichos datos se recoger&iacute;an a trav&eacute;s de grabaciones de navegaci&oacute;n, mapas de calor y otro tipo de informes estrictamente con fines de an&aacute;lisis y mejora del portal.</p>
				
				

			</div>
		</div>
	</section>
	<!--================End Login Box Area =================-->

<?php $__env->stopSection(); ?>

<?php echo $__env->make('website_layout.layout', array_except(get_defined_vars(), array('__data', '__path')))->render(); ?>